

mybatis: 
    mapperLocations: /mapper/**/*.xml
    
spring.datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mybatis
    username: postgres
    password: jie123456
    poolName: SpringBootHikariCP
    maximumPoolSize: 20
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000
    pool-prepared-statements: true
    max-open-prepared-statements: 250
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: true
    
logging:
    level.com.yuehuanghun: debug