

datasources:
  example1: 
    ds: 
      jdbcUrl: jdbc:mysql://localhost:3306/example1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&tinyInt1isBit=true
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      maxPoolSize: 10
      connectionTestQuery: select 1
    mybatis:
      # 搜索指定包别名
      typeAliasesPackage: com.yuehuanghun.mybatis.milu.example.example1.domain
      # 配置mapper的扫描，找到所有的mapper.xml映射文件
      mapperLocations: classpath*:mapper/example1/*Mapper.xml
      # 加载全局的配置文件
      configLocation: classpath:mybatis/mybatis-config.xml
  example2: 
    ds: 
      jdbcUrl: jdbc:mysql://localhost:3306/example2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&tinyInt1isBit=true
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      maxPoolSize: 10
      connectionTestQuery: select 1
    mybatis:
      # 搜索指定包别名
      typeAliasesPackage: com.yuehuanghun.mybatis.milu.example.example2.domain
      # 配置mapper的扫描，找到所有的mapper.xml映射文件
      mapperLocations: classpath*:mapper/example2/*Mapper.xml
      # 加载全局的配置文件
      configLocation: classpath:mybatis/mybatis-config.xml
      
pagehelper: 
  helperDialect: mysql    #一般情况下自动识别数据库即可
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 
    