

mybatis: 
    mapperLocations: /mapper/**/*.xml
    identifierWrapQuote: true
    configurationProperties: 
        idGenerator: snowflake
        exampleQueryConverter: com.yuehuanghun.mybatismilu.test.config.MyExampleQueryConverter
    
spring.datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    poolName: SpringBootHikariCP
    maximumPoolSize: 20
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000
    pool-prepared-statements: true
    max-open-prepared-statements: 250
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: true
    
logging:
    level.com.yuehuanghun: debug
    file: ./logs/milutest.log